apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - injector-deployment.yaml
  - injector-mutating-webhook.yaml
  - injector-rbac.yaml
  - injector-service.yaml
  - injector-leader-extras.yaml

#create an inline patch for environment variables

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/6/value
        value: "registry.sighup.io/fury/vault/vault:1.12.3"

images:
  - name: vault-k8s
    newName: registry.sighup.io/fury/vault/vault-k8s
    newTag: 1.2.0
