---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - vendor/katalog/vault/aws
  - vendor/katalog/vault/sidecar-injector

secretGenerator:
  - files:
      - config/autounseal.hcl
      - config/backend.hcl
    behavior: merge
    name: vault

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: vault-injector
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/5/value
        value: "http://vault.$(NAMESPACE).svc:8200"
